version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  task4_app:
    image: anderson954/myapp
    container_name: task4_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - ASPNETCORE_URLS=http://+:8080 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__default=Host=postgres;Username=postgres;Password=123;Database=db;Port=5432;
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - my_network
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=anderson64217@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "105:80"
    networks:
      - my_network

volumes:
  db_data: